"""add table material_files

Revision ID: 001bd8db2218
Revises: 06291a827af1
Create Date: 2025-04-19 18:43:41.847262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001bd8db2218'
down_revision: Union[str, None] = '06291a827af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_files',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('material_id', sa.Integer(), nullable=False),
                    sa.Column('file_name', sa.String(
                        length=255), nullable=True),
                    sa.Column('file_description', sa.String(
                        length=255), nullable=True),
                    sa.Column('file_url', sa.String(
                        length=255), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['material_id'], ['materials.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.alter_column('materials', 'name',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True
                    )
    op.drop_column('materials', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('url', sa.VARCHAR(
        length=255), autoincrement=False, nullable=True))
    op.alter_column('materials', 'name',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    op.drop_table('material_files')
    # ### end Alembic commands ###
