"""add column hours to table Courses

Revision ID: 58901a5f6d2a
Revises: e9374f83547d
Create Date: 2025-05-07 16:31:53.301580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58901a5f6d2a'
down_revision: Union[str, None] = 'e9374f83547d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'hours')
    # ### end Alembic commands ###
